/*
This vertex shader was autogenerated by the Higgs particle editor.

Higgs -->
eJydkbEOgjAQhrv6NgWUthuJE5tG4+zRO0wNUFILYfQNfCUeTSLg4ATecst9d9+faznbsLEA8UI6ZJGAONwprbkOEChUCoSM461U
mOc8w2n8nHzaFXvb+Lrxe1tYtxBOXiOc3JMRTku40Ur4eZzgU+2MX09P3gf7MN7Yig0cl8gDqQiyPEQRcBGAjDQXPM628Kver1Hu
57xUGu/Jfa+uWzBkrsF5owtKK6RusfSM9y05T92f54fQ0/fZG9vvkSg=
<-- Higgs
*/

attribute vec3 in_Position;
attribute vec4 in_Colour;
attribute vec2 in_TextureCoord;

varying vec2 v_vTexcoord;
varying vec4 v_vColour;

void main()
{
    gl_Position = gm_Matrices[MATRIX_WORLD_VIEW_PROJECTION]*vec4(in_Position.xyz, 1.0);
    v_vColour   = in_Colour;
    v_vTexcoord = in_TextureCoord;
}
